### ISSUE TITLE
Add flymake

### ISSUE THREAD

**Issue by tkg** [TreeRex/rnc-mode#2]
Consider adding the running of Jing on files using `flymake' along the lines of http://inasmuch.as/2012/02/22/flymake-for-relax-ng-compact-syntax/

To do it properly for a multi-file schema, however, would require running Jing on the file containing the 'start' pattern, which might not be the current file.

**Comment by TreeRex** [comment]
Added for single-file schema, though I tested with Norman Walsh's XSLT 1.0/2.0/3.0 schema and it worked fine. If you have an example of a multifile schema that doesn't work correctly I'll take a look.
